/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nagyfeladat;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Admin
 */
public class Belepes extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
static  String Nev=null;
static  String Azon=null;
static String F_kod=null;
//static final Integer Kod=null;
//static final Boolean Tipus=null;


    /**
     * Creates new form Belepes
     */
    public Belepes() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Belepes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_Felhasznalo = new javax.swing.JTextField();
        jPF_jelszo = new javax.swing.JPasswordField();
        jB_Belep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 0, 0));

        jPanel_Belepes.setBackground(new java.awt.Color(204, 102, 0));
        jPanel_Belepes.setForeground(new java.awt.Color(102, 51, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Felhasználó:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Jelszó:");

        jTF_Felhasznalo.setBackground(new java.awt.Color(255, 255, 153));
        jTF_Felhasznalo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jPF_jelszo.setBackground(new java.awt.Color(255, 255, 153));
        jPF_jelszo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jB_Belep.setBackground(new java.awt.Color(255, 153, 51));
        jB_Belep.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jB_Belep.setForeground(new java.awt.Color(51, 0, 51));
        jB_Belep.setText("Belépés");
        jB_Belep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BelepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BelepesLayout = new javax.swing.GroupLayout(jPanel_Belepes);
        jPanel_Belepes.setLayout(jPanel_BelepesLayout);
        jPanel_BelepesLayout.setHorizontalGroup(
            jPanel_BelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BelepesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel_BelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_Felhasznalo)
                    .addComponent(jPF_jelszo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BelepesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_Belep, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel_BelepesLayout.setVerticalGroup(
            jPanel_BelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BelepesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_Felhasznalo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_BelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BelepesLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_BelepesLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPF_jelszo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jB_Belep)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Belepes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Belepes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_BelepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BelepActionPerformed
        Boolean ok=true;
        conn=EnSqlkapcsolatom.ConnectDB();
        String sql="Select * from Felhasznalo where F_nev=? and F_azonosito=?";
        try
        {
                pst=conn.prepareStatement(sql);
                pst.setString(1,jTF_Felhasznalo.getText());
                pst.setString(2,jPF_jelszo.getText());
                rs=pst.executeQuery();
                              
                if (rs.next())
                {
                        JOptionPane.showMessageDialog(null,"Üdvözlöm!");
                        
                        Nev=jTF_Felhasznalo.getText();
                        Azon=jPF_jelszo.getText();
                        Fomenu f=new Fomenu();
                        f.setVisible(true);
                        setVisible(false);
                }
                else
                {
                        JOptionPane.showMessageDialog(null, "Hibás Felhasználónév, vagy jelszó","Hozzáfárás megtagadva!", JOptionPane.ERROR_MESSAGE);
                        ok=false;
                }
                pst.close();
                conn.close();
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null,e);
        }
        if (ok)
        {
            try
            {
                conn=EnSqlkapcsolatom.ConnectDB();
                Statement sta = conn.createStatement();
                String sqltcs="Select F_kod from felhasznalo where F_nev='"+Nev+"' and F_azonosito='"+Azon+"'";
                //System.out.println(sqltcs);
                ResultSet rs= sta.executeQuery(sqltcs);
                if (rs.next())
                {
                    F_kod=rs.getString("F_kod");
                    //System.out.println(F_kod);
                }
                sta.close();
                conn.close();
                
            }
            catch(Exception e)
            {
                 JOptionPane.showMessageDialog(null, "F_kod sikertelen!");
            }
        }
            
    }//GEN-LAST:event_jB_BelepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Belepes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Belepes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Belepes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Belepes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
              //  new Belepes().setVisible(true); 
          //  }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Belep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPF_jelszo;
    private javax.swing.JPanel jPanel_Belepes;
    private javax.swing.JTextField jTF_Felhasznalo;
    // End of variables declaration//GEN-END:variables
}
