/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nagyfeladat;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Fomenu extends javax.swing.JFrame {
static  Integer Allapot=null;
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form Fomenu
     */
    
    public Fomenu() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel_Fomenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Karb = new javax.swing.JMenu();
        jMI_ujF = new javax.swing.JMenuItem();
        jMI_UjTermek = new javax.swing.JMenuItem();
        jM_Tcs = new javax.swing.JMenuItem();
        jM_Ugyv = new javax.swing.JMenu();
        jMI_Eladas = new javax.swing.JMenuItem();
        jMI_Kimutatas = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel_Fomenu.setBackground(new java.awt.Color(255, 204, 102));
        jPanel_Fomenu.setForeground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nagyfeladat/pic/bolt.jpg"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel_FomenuLayout = new javax.swing.GroupLayout(jPanel_Fomenu);
        jPanel_Fomenu.setLayout(jPanel_FomenuLayout);
        jPanel_FomenuLayout.setHorizontalGroup(
            jPanel_FomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_FomenuLayout.setVerticalGroup(
            jPanel_FomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jM_Karb.setText("Karbantartás");
        jM_Karb.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMI_ujF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMI_ujF.setText("Új Felhasználó");
        jMI_ujF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ujFActionPerformed(evt);
            }
        });
        jM_Karb.add(jMI_ujF);

        jMI_UjTermek.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMI_UjTermek.setText("Új_Termék/Termek módosítás");
        jMI_UjTermek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_UjTermekActionPerformed(evt);
            }
        });
        jM_Karb.add(jMI_UjTermek);

        jM_Tcs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jM_Tcs.setText("Új termékcsoport");
        jM_Tcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_TcsActionPerformed(evt);
            }
        });
        jM_Karb.add(jM_Tcs);

        jMenuBar1.add(jM_Karb);

        jM_Ugyv.setText("Ügyvitel");
        jM_Ugyv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMI_Eladas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMI_Eladas.setText("Eladás");
        jMI_Eladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_EladasActionPerformed(evt);
            }
        });
        jM_Ugyv.add(jMI_Eladas);

        jMI_Kimutatas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMI_Kimutatas.setText("Kimutatás");
        jMI_Kimutatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_KimutatasActionPerformed(evt);
            }
        });
        jM_Ugyv.add(jMI_Kimutatas);

        jMenuBar1.add(jM_Ugyv);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Fomenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Fomenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        conn=EnSqlkapcsolatom.ConnectDB();
        //System.out.println(Belepes.Azon+" "+Belepes.Nev);
        String sql="Select * from Felhasznalo where F_nev='"+Belepes.Nev+"'"
                                + " and F_azonosito='"+Belepes.Azon+"'";
        try
        {
            Statement sta = conn.createStatement();
            ResultSet rs= sta.executeQuery(sql);
            rs.next();
            Allapot=(Integer.parseInt(rs.getString("F_tipus")));
            //System.out.println(Allapot);
            if (Allapot==1)
            {
                jM_Karb.setEnabled(true);
                jMI_ujF.setEnabled(true);
                jMI_UjTermek.setEnabled(true);
                jM_Tcs.setEnabled(true);
                jM_Ugyv.setEnabled(true);
                jMI_Eladas.setEnabled(true);
                jMI_Kimutatas.setEnabled(true);  
            }
            else
            {
                jM_Karb.setEnabled(true);
                jMI_ujF.setEnabled(false);
                jMI_UjTermek.setEnabled(true);
                jM_Tcs.setEnabled(true);
                jM_Ugyv.setEnabled(true);
                jMI_Eladas.setEnabled(true);
                jMI_Kimutatas.setEnabled(false);
            }
            sta.close();
            conn.close();
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jMI_ujFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ujFActionPerformed
         Uj_Felhasznalo uf=new Uj_Felhasznalo();
         uf.setVisible(true);
    }//GEN-LAST:event_jMI_ujFActionPerformed

    private void jM_TcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_TcsActionPerformed
         Uj_Termekcsoport utcs=new Uj_Termekcsoport();
         utcs.setVisible(true);
    }//GEN-LAST:event_jM_TcsActionPerformed

    private void jMI_UjTermekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_UjTermekActionPerformed
         Uj_Termek_Termekmodositas uttm=new Uj_Termek_Termekmodositas();
         uttm.setVisible(true);
    }//GEN-LAST:event_jMI_UjTermekActionPerformed

    private void jMI_EladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_EladasActionPerformed
        Eladas ela=new Eladas();
         ela.setVisible(true);
    }//GEN-LAST:event_jMI_EladasActionPerformed

    private void jMI_KimutatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_KimutatasActionPerformed
        Lekerdezes lek=new Lekerdezes();
        lek.setVisible(true);
    }//GEN-LAST:event_jMI_KimutatasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fomenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMI_Eladas;
    private javax.swing.JMenuItem jMI_Kimutatas;
    private javax.swing.JMenuItem jMI_UjTermek;
    private javax.swing.JMenuItem jMI_ujF;
    private javax.swing.JMenu jM_Karb;
    private javax.swing.JMenuItem jM_Tcs;
    private javax.swing.JMenu jM_Ugyv;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel_Fomenu;
    // End of variables declaration//GEN-END:variables
}
