/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nagyfeladat;
import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Uj_Felhasznalo extends javax.swing.JFrame {
static  Integer Allapot=null;
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
String Nevellenorzes=null;
    /**
     * Creates new form Uj_Felhasznalo
     */
    public Uj_Felhasznalo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nev = new javax.swing.JLabel();
        jT_Nev = new javax.swing.JTextField();
        Nev1 = new javax.swing.JLabel();
        Nev2 = new javax.swing.JLabel();
        jPF_1 = new javax.swing.JPasswordField();
        jPF_2 = new javax.swing.JPasswordField();
        jB_jovahagy = new javax.swing.JButton();
        jB_Vissza = new javax.swing.JButton();
        jCB_1 = new javax.swing.JCheckBox();
        jL_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nev.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Nev.setText("Név:");

        jT_Nev.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Nev1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Nev1.setText("Jelszó");

        Nev2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Nev2.setText("Jelszó ismétlés");

        jPF_1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jPF_2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPF_2.setToolTipText("");

        jB_jovahagy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jB_jovahagy.setText("Felvétel");
        jB_jovahagy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_jovahagyActionPerformed(evt);
            }
        });

        jB_Vissza.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jB_Vissza.setText("Vissza");
        jB_Vissza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VisszaActionPerformed(evt);
            }
        });

        jCB_1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCB_1.setText("Rendszergazda");
        jCB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_1ActionPerformed(evt);
            }
        });

        jL_info.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nev1)
                    .addComponent(Nev)
                    .addComponent(Nev2))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jT_Nev)
                    .addComponent(jPF_1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jPF_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCB_1)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_jovahagy, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jB_Vissza, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nev)
                    .addComponent(jT_Nev, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Nev1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Nev2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPF_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB_1))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_jovahagy)
                    .addComponent(jB_Vissza))
                .addGap(42, 42, 42)
                .addComponent(jL_info, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_1ActionPerformed

    private void jB_VisszaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VisszaActionPerformed
        dispose();
    }//GEN-LAST:event_jB_VisszaActionPerformed

    private void jB_jovahagyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_jovahagyActionPerformed
        jL_info.setText("");
        boolean ok=true;
        for (int i = 0; i < jT_Nev.getText().length(); i++) 
        {
            {
                char ellenorzes=jT_Nev.getText().charAt(i);
                if (ellenorzes==' ')
                {
                    ok=false;
                    jL_info.setText("Ne hagyjon space karaktert!");
                }
            }
        }
        if (ok)
        {
            if (jT_Nev.getText().equals("") || jPF_1.getText().equals(""))
            {
                jL_info.setText("Ne hagyjon üres mezőket!");
                ok=false;
            }
            else if (!(jPF_1.getText().equals(jPF_2.getText())))
            {
                jL_info.setText("Jelszó megerősítés nem megfelelő");
                ok=false;
            }
            else
            {
                conn=EnSqlkapcsolatom.ConnectDB();
                // System.out.println(Belepes.Azon+" "+Belepes.Nev);
                String sql="Select F_nev from Felhasznalo where F_nev='"+jT_Nev.getText()+"'";
                try
                {
                    Statement sta = conn.createStatement();
                    ResultSet rs= sta.executeQuery(sql);
                    if (rs.next())
                    {
                       Nevellenorzes=rs.getString("F_nev");
                       System.out.println(Nevellenorzes);
                       jL_info.setText("Ez a név már szerepel!");
                       ok=false; 
                    }
                    sta.close();
                    conn.close(); 
                }
                catch(Exception e)
                {
                        JOptionPane.showMessageDialog(null,e);
                }
            }
        }
        if (ok)
        {
            try
                {
                    int jog=0;
                    if (jCB_1.isSelected())
                    {
                        jog=1;
                    }
                    conn=EnSqlkapcsolatom.ConnectDB();
                    Statement sta = conn.createStatement();
                    String sqlin="INSERT INTO Felhasznalo (F_nev, F_azonosito, F_tipus) VALUES "
                     +"('"+jT_Nev.getText()+"',"
                     +"'"+jPF_1.getText()+"',"
                     +jog+")";
                    Statement st=conn.createStatement();
                    st.executeUpdate(sqlin);         
                    JOptionPane.showMessageDialog(null, "Insert megtörtént!");
                    sta.close();
                    conn.close(); 
                    this.dispose();
                }
                catch(Exception e)
                {
                    System.out.println("Hiba"+e);
                    JOptionPane.showMessageDialog(null, "Sikertelen felvétel!");
                }
        }
    }//GEN-LAST:event_jB_jovahagyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uj_Felhasznalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uj_Felhasznalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uj_Felhasznalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uj_Felhasznalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uj_Felhasznalo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nev;
    private javax.swing.JLabel Nev1;
    private javax.swing.JLabel Nev2;
    private javax.swing.JButton jB_Vissza;
    private javax.swing.JButton jB_jovahagy;
    private javax.swing.JCheckBox jCB_1;
    private javax.swing.JLabel jL_info;
    private javax.swing.JPasswordField jPF_1;
    private javax.swing.JPasswordField jPF_2;
    private javax.swing.JTextField jT_Nev;
    // End of variables declaration//GEN-END:variables
}
