/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nagyfeladat;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Uj_Termekcsoport extends javax.swing.JFrame {
static  Integer Allapot=null;
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
String Nevellenorzes=null;
    /**
     * Creates new form Uj_Termekcsoport
     */
    public Uj_Termekcsoport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tcsk = new javax.swing.JLabel();
        jL_tcsn = new javax.swing.JLabel();
        jB_Felvetel = new javax.swing.JButton();
        jB_Vissza = new javax.swing.JButton();
        jTF_tcsk = new javax.swing.JTextField();
        jTF_tcsn = new javax.swing.JTextField();
        jL_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_tcsk.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jL_tcsk.setText("Termékcsoport kód:");

        jL_tcsn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jL_tcsn.setText("termekcsoport név:");

        jB_Felvetel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jB_Felvetel.setText("Felvétel");
        jB_Felvetel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_FelvetelActionPerformed(evt);
            }
        });

        jB_Vissza.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jB_Vissza.setText("Vissza");
        jB_Vissza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VisszaActionPerformed(evt);
            }
        });

        jTF_tcsk.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTF_tcsk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_tcskKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_tcskKeyTyped(evt);
            }
        });

        jTF_tcsn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTF_tcsn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_tcsnKeyTyped(evt);
            }
        });

        jL_info.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_tcsn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_tcsk, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_tcsn, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_tcsk, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Felvetel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(337, 337, 337)
                                .addComponent(jB_Vissza, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_tcsk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_tcsk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jL_tcsn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jTF_tcsn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Felvetel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Vissza, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jL_info, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_tcskKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_tcskKeyTyped
        char c = evt.getKeyChar();
        if (jTF_tcsk.getText().equals(""))
        {
           if ( ((c < '1') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) 
           {
                evt.consume();  // ha nem szám, akkor ignorálja
           } 
        }
        else
        {
            if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) 
            {
                evt.consume();  // ha nem szám, akkor ignorálja
            } 
        }  
    }//GEN-LAST:event_jTF_tcskKeyTyped

    private void jTF_tcskKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_tcskKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_tcskKeyPressed

    private void jTF_tcsnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_tcsnKeyTyped
        char c = evt.getKeyChar();
        if ((c < ' ') && (c != KeyEvent.VK_BACK_SPACE)) 
           {
                evt.consume();  // ha space, akkor ignorálja
           } 
    }//GEN-LAST:event_jTF_tcsnKeyTyped

    private void jB_VisszaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VisszaActionPerformed
        dispose();
    }//GEN-LAST:event_jB_VisszaActionPerformed

    private void jB_FelvetelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_FelvetelActionPerformed
        jL_info.setText("");
        boolean ok=true;
        if (ok)
        {
            if (jTF_tcsk.getText().equals("") || jTF_tcsn.getText().equals(""))
            {
                jL_info.setText("Ne hagyjon üres mezőket!");
                ok=false;
            }
            else
            {
                conn=EnSqlkapcsolatom.ConnectDB();
                String sql="Select * from Termekcsoport where Tcs_kod='"+jTF_tcsk.getText()+"'";
                try
                {
                    Statement sta = conn.createStatement();
                    ResultSet rs= sta.executeQuery(sql);
                    if (rs.next())
                    {
                       Nevellenorzes=rs.getString("Tcs_kod");
                       System.out.println(Nevellenorzes);
                       jL_info.setText("Ez a kód már szerepel!");
                       ok=false; 
                    }
                    sta.close();
                    conn.close(); 
                }
                catch(Exception e)
                {
                        JOptionPane.showMessageDialog(null,e);
                }
                conn=EnSqlkapcsolatom.ConnectDB();
                sql="Select * from Termekcsoport where Tcs_nev='"+jTF_tcsn.getText()+"'";
                try
                {
                    Statement sta = conn.createStatement();
                    ResultSet rs= sta.executeQuery(sql);
                    if (rs.next())
                    {
                       Nevellenorzes=rs.getString("Tcs_nev");
                       System.out.println(Nevellenorzes);
                       jL_info.setText("Ez a termekcsoport már létezik!");
                       ok=false; 
                    }
                    sta.close();
                    conn.close(); 
                }
                catch(Exception e)
                {
                        JOptionPane.showMessageDialog(null,e);
                }
            }
        }
        if (ok)
        {
            try
                {
                    conn=EnSqlkapcsolatom.ConnectDB();
                    String sqlin="INSERT INTO Termekcsoport (Tcs_kod, Tcs_nev) VALUES "
                     +"('"+jTF_tcsk.getText()+"',"
                     +"'"+jTF_tcsn.getText()+"')";
                    Statement st=conn.createStatement();
                    st.executeUpdate(sqlin);         
                    JOptionPane.showMessageDialog(null, "Insert megtörtént!");
                    st.close();
                    conn.close(); 
                    this.dispose();
                }
                catch(Exception e)
                {
                    System.out.println("Hiba"+e);
                    JOptionPane.showMessageDialog(null, "Sikertelen felvétel!");
                }
        }
    }//GEN-LAST:event_jB_FelvetelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uj_Termekcsoport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uj_Termekcsoport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uj_Termekcsoport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uj_Termekcsoport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uj_Termekcsoport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Felvetel;
    private javax.swing.JButton jB_Vissza;
    private javax.swing.JLabel jL_info;
    private javax.swing.JLabel jL_tcsk;
    private javax.swing.JLabel jL_tcsn;
    private javax.swing.JTextField jTF_tcsk;
    private javax.swing.JTextField jTF_tcsn;
    // End of variables declaration//GEN-END:variables
}
